# Generated by Django 5.1.7 on 2025-03-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ticker',), name='unique_ticker')],
            },
        ),
    ]
